words = [
    "vikram",
    "kaithi",
    "master",
    "leo",
    "jailer",
    "beast",
    "varisu",
    "ghilli",
    "thuppakki",
    "mersal",

    "theri",
    "bigil",
    "vettaiyan",
    "jailer",
    "petta",
    "darbar",
    "kabali",
    "enthiran",
    "sivaji",
    "padayappa",

    "anbe sivam",
    "pudhupettai",
    "vada chennai",
    "visaranai",
    "pariyerum perumal",
    "soorarai pottru",
    "jai bhim",
    "asuran",
    "karnan",
    "96",

    "vada chennai",
    "theeran adhigaaram ondru",
    "dheena",
    "polladhavan",
    "aadukalam",
    "subramaniapuram",
    "sathuranga vettai",
    "maanadu",
    "irumbu thirai",
    "kaithi",

    "love today",
    "don",
    "doctor",
    "good night",
    "parking",
    "lubber pandhu",
    "maaveeran",
    "mark antony",
    "por thozhil",
    "dada",

    "super deluxe",
    "joker",
    "suzhal",
    "meyaadha maan",
    "soodhu kavvum",
    "moodar koodam",
    "onaayum aattukkuttiyum",
    "indru netru naalai",
    "oh my kadavule",
    "thadam",

    "96",
    "ok kanmani",
    "vinnai thaandi varuvaayaa",
    "raja rani",
    "alaipayuthey",
    "vaaranam aayiram",
    "autograph",
    "kadhalum kadandhu pogum",
    "raatchasan",
    "demonte colony",

    "kandukondain kandukondain",
    "mudhalvan",
    "rhythm",
    "jeans",
    "boys",
    "anbe sivam",
    "panchathanthiram",
    "vasool raja mbbs",
    "michael madana kama rajan",
    "avvai shanmughi",

    "arunachalam",
    "muthu",
    "baasha",
    "padayappa",
    "sivaji",
    "annamalai",
    "thalapathi",
    "mankatha",
    "billa",
    "dil se"
]

clues = [
    "A mysterious man arrives in a city with a dangerous mission",
    "A prisoner escapes and becomes involved in a drug operation",
    "A professor becomes an unlikely action hero",
    "A man with a violent past tries to protect his family",
    "A powerful prison warden takes on a criminal empire",
    "A former agent becomes involved with a dangerous organization",
    "A family drama involving inheritance and relationships",
    "A local tough guy gets involved in a conflict with a powerful businessman",
    "An intelligence officer takes on a major terrorist threat",
    "A man with multiple identities fights against a criminal organization",

    "A police officer fights to protect a young girl",
    "A football club becomes the center of a major conflict",
    "A veteran hunter gets involved in a dangerous mission",
    "A gangster's story involving politics and revenge",
    "A gangster returns to settle old scores",
    "A police officer takes on an international criminal network",
    "A gangster struggles with his past and identity",
    "A scientist creates a humanoid robot",
    "A man becomes a powerful politician after exposing corruption",
    "A powerful man tries to protect his family and legacy",

    "Two men with completely different personalities develop an unusual friendship",
    "A gangster's rise and fall in the criminal world of North Chennai",
    "A young man's life becomes connected to the dangerous world of North Chennai",
    "A group of prisoners face brutal interrogation",
    "A young woman challenges caste discrimination",
    "A pilot dreams of starting his own low-cost airline",
    "A lawyer fights for the rights of tribal people",
    "A farmer seeks revenge against those who destroy his life",
    "A man fights against a corrupt system while searching for justice",
    "Two people reconnect years after their school romance",

    "A young man becomes trapped in the world of organized crime",
    "An undercover police officer hunts down a dangerous criminal",
    "A young man becomes a local gangster",
    "A man's stolen motorcycle leads him into the criminal world",
    "A young man becomes involved in illegal cockfighting",
    "A group of criminals plan an unusual robbery",
    "A group of criminals compete in a bizarre game",
    "A mysterious time-loop creates chaos during a political election",
    "A cyber-security specialist fights against a powerful corporation",
    "A prisoner becomes the center of a dangerous drug operation",

    "A young man tries to prove himself after a breakup",
    "A college student gets involved in a series of unexpected events",
    "A doctor secretly fights criminals while working at a hospital",
    "A man develops an unexpected friendship with his neighbor",
    "A parking dispute between two neighbors becomes increasingly intense",
    "Two young people from different backgrounds bond through kabaddi",
    "A man discovers a mysterious connection involving his past",
    "A criminal and an aspiring actor become connected through a bizarre incident",
    "A police officer investigates a series of mysterious murders",
    "A young couple deals with an unexpected pregnancy",

    "A dysfunctional family becomes involved in a strange crime",
    "A man investigates corruption while pretending to be someone else",
    "A woman investigates a mysterious disappearance in a village",
    "A young man struggles with love and family expectations",
    "A group of criminals attempt to survive a dangerous night",
    "A man becomes obsessed with finding his missing dog",
    "A group of friends get into trouble after finding something valuable",
    "A group of people wake up in a mysterious situation",
    "A man discovers that his actions are connected to the future",
    "A man struggles with life after making a supernatural mistake",

    "Two lovers struggle to reconnect after years apart",
    "A couple falls in love while dealing with family conflicts",
    "A young couple's relationship is tested by their families",
    "A man tries to win back his former lover",
    "A couple discovers that their relationship is affected by destiny",
    "A man documents his life and relationships through the years",
    "Two strangers slowly develop feelings for each other",
    "A police officer hunts a dangerous serial killer",
    "A group of friends encounter supernatural events in an abandoned building",

    "Two people meet through a matchmaking situation",
    "A politician exposes corruption within the government",
    "Several strangers become connected through music and love",
    "A fashion designer becomes involved in an unusual adventure",
    "A group of college students experience friendship and romance",
    "Two very different men form an unexpected friendship",
    "A doctor gets involved in a hilarious series of situations",
    "A man with multiple personalities creates complete chaos",
    "A man pretends to be someone else to win a woman's heart",
    "A woman disguises herself as a man to escape a difficult situation",

    "A wealthy man returns to his hometown to solve family problems",
    "A gangster rules the underworld while protecting his family",
    "A powerful don returns to confront his enemies",
    "A wealthy man fights to protect his family business",
    "A politician faces enemies while trying to protect his legacy",
    "A gangster becomes involved in a dangerous political conflict",
    "A mysterious man arrives in a village and changes everything",
    "A group of friends get involved in a massive betting scheme",
    "A mysterious man with a violent past returns",
    "A man travels to another country while searching for his lover"
]