words = [
    "skibidi",
    "rizz",
    "gyatt",
    "sigma",
    "fanumtax",
    "looksmaxxing",
    "mewing",
    "mogging",
    "aura",
    "brainrot",

    "delulu",
    "yapping",
    "yapper",
    "cooked",
    "crashout",
    "lockedin",
    "goated",
    "bussin",
    "mid",
    "based",

    "cap",
    "nocap",
    "sus",
    "slay",
    "pookie",
    "bruh",
    "bro",
    "sheesh",
    "frfr",
    "ngl",

    "iykyk",
    "lmao",
    "lol",
    "wtf",
    "imo",
    "tbh",
    "irl",
    "afk",
    "npc",
    "maincharacter",

    "sidequest",
    "glowup",
    "situationship",
    "redflag",
    "greenflag",
    "ick",
    "ghosting",
    "simp",
    "stan",
    "clout",

    "influencer",
    "clickbait",
    "ragebait",
    "engagement",
    "viral",
    "reels",
    "algorithm",
    "fyp",
    "commentsection",
    "shitpost",

    "brainrot",
    "chronicallyonline",
    "touchgrass",
    "parasocial",
    "doomscrolling",
    "oversharing",
    "unhinged",
    "feral",
    "yapfest",
    "cringe"
]

clues = [
    "A word associated with a strangely iconic internet toilet-themed phenomenon",
    "A mysterious ability to attract romantic attention through words",
    "An exaggerated compliment for someone's appearance",
    "A lone-wolf internet archetype who supposedly needs nobody",
    "The unofficial fee you pay when someone steals your food",
    "The obsessive pursuit of improving one's physical appearance",
    "A silent facial exercise involving the tongue and jaw",
    "Looking noticeably better or more impressive than someone else",
    "An invisible social score that supposedly rises after impressive moments",
    "Content so repetitive that it damages your remaining attention span",

    "Having unrealistic confidence about a romantic situation",
    "Talking continuously without providing much useful information",
    "Someone who appears to have unlimited things to say",
    "A situation where success seems increasingly unlikely",
    "An explosive emotional reaction after reaching the limit",
    "Giving something your complete attention and effort",
    "A legendary compliment for something exceptionally good",
    "A reaction describing food that is unbelievably good",
    "A painfully average result that inspires little excitement",
    "Agreeing with an opinion because it feels undeniably correct",

    "A lie or something that isn't true",
    "An emphatic way of saying you're being completely serious",
    "Suspicious behavior that makes you question someone's intentions",
    "An enthusiastic approval of someone's behavior or appearance",
    "An overly affectionate nickname for someone",
    "A reaction to something unbelievably ridiculous",
    "A casual term for a male friend",
    "An expression used when something is extremely impressive",
    "An exaggerated version of saying 'for real'",
    "A short way of admitting your honest opinion",

    "A phrase meaning only certain people will understand",
    "A reaction associated with finding something extremely funny",
    "A short expression of amusement",
    "A reaction to something shocking, confusing, or ridiculous",
    "A short way to state your personal opinion",
    "A short way of saying you're being honest",
    "Short for something happening in real life",
    "Being away from the keyboard",
    "A person who behaves as if they are controlled by a game script",
    "Acting as though your life is the plot of a movie",

    "An unnecessary adventure that happens while avoiding your main task",
    "A dramatic improvement in someone's appearance or lifestyle",
    "A romantic connection that refuses to become an official relationship",
    "A behavior suggesting someone might cause problems in a relationship",
    "A sign suggesting someone would be a healthy partner",
    "A tiny behavior that suddenly makes someone unattractive to you",
    "Disappearing from someone's life without explanation",
    "Someone who gives excessive attention to a romantic interest",
    "A person who is extremely devoted to a celebrity or creator",
    "Attention or popularity gained online",

    "A person who earns attention by creating online content",
    "A title designed mainly to make you click",
    "Content deliberately designed to make people angry",
    "Interactions such as likes, comments, and shares",
    "Content spreading extremely quickly across the internet",
    "Short-form videos commonly watched through social media",
    "The mysterious system deciding what appears on your feed",
    "The personalized feed where the algorithm sends you",
    "The digital battlefield where strangers argue",
    "An intentionally ridiculous or absurd internet post",

    "Internet content that has completely destroyed your attention span",
    "Spending so much time online that normal life feels unfamiliar",
    "A reminder to leave the internet and experience actual nature",
    "A one-sided emotional attachment to an online personality",
    "Mindlessly consuming negative content for hours",
    "Sharing extremely personal information online",
    "Wildly chaotic behavior with almost no restraint",
    "Acting completely chaotic and uncontrollable",
    "A gathering where everyone talks and nobody listens",
    "Something so awkward that you desperately want to look away"
]